# Generated by Django 5.2.3 on 2025-07-16 11:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_parent', models.IntegerField(blank=True, null=True)),
                ('id_filial', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('long_name', models.CharField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, null=True)),
                ('set_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_filial', models.IntegerField(blank=True, null=True)),
                ('id_department', models.IntegerField(blank=True, null=True)),
                ('post_name', models.CharField(blank=True, null=True)),
                ('tabnumber', models.IntegerField(unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('set_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, null=True)),
                ('long_name', models.CharField(blank=True, null=True)),
                ('short_name', models.CharField(blank=True, null=True)),
                ('set_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('boss', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Администратор сервиса',
                'verbose_name_plural': 'Администраторы сервиса',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='tables.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rows', to=settings.AUTH_USER_MODEL)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.filial')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RowLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField()),
                ('row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock', to='tables.row')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_locks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('share_token', models.CharField(blank=True, max_length=32, unique=True)),
                ('is_edit_only_you', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='row',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='tables.table'),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False, help_text='Если отмечено, поле должно быть заполнено при создании/редактировании строки', verbose_name='Обязательное поле')),
                ('data_type', models.CharField(choices=[('text', 'Текст'), ('integer', 'Целое число'), ('pos_integer', 'Целое число больше нуля'), ('float', 'Число с плавающей точкой'), ('boolean', 'Логическое'), ('date', 'Дата'), ('email', 'Почта'), ('url', 'Ссылка'), ('file', 'Файл'), ('choice', 'Выбор из списка')], default='text', max_length=12)),
                ('choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tables.table')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TableFilialPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('RWD', 'Редактировать + Просмотр + Удалять'), ('RWN', 'Редактировать + Просмотр'), ('RNN', 'Только просмотр'), ('NNN', 'Нет доступа')], default='RWD', max_length=3, verbose_name='Тип доступа')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.filial')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_permissions', to='tables.table')),
            ],
        ),
        migrations.CreateModel(
            name='TablePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('RWD', 'Редактировать + Просмотр + Удалять'), ('RWN', 'Редактировать + Просмотр'), ('RNN', 'Только просмотр'), ('NNN', 'Нет доступа')], default='RWD', max_length=3, verbose_name='Тип доступа')),
                ('filial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.filial')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tables.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.filial')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('positive_integer_value', models.PositiveIntegerField(blank=True, null=True)),
                ('email_value', models.EmailField(blank=True, max_length=254, null=True)),
                ('url_value', models.URLField(blank=True, null=True)),
                ('file_value', models.FileField(blank=True, null=True, upload_to='files/')),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('choice_value', models.TextField(blank=True, max_length=255, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.column')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='tables.row')),
            ],
            options={
                'unique_together': {('row', 'column')},
            },
        ),
        migrations.CreateModel(
            name='TableFilialLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField()),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.filial')),
                ('locked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_add_permissions', to='tables.table')),
            ],
            options={
                'unique_together': {('table', 'filial')},
            },
        ),
    ]
