# Generated by Django 5.2.3 on 2025-07-16 15:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_column_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='last_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 15, 4, 57, 616455)),
        ),
        migrations.AddField(
            model_name='row',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_rows', to=settings.AUTH_USER_MODEL),
        ),
    ]
