# Generated by Django 5.2.3 on 2025-07-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_row_last_date_row_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
