# Generated by Django 5.2.3 on 2025-07-08 08:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0021_column_is_required_alter_admin_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 8, 42, 24, 216181)),
        ),
        migrations.CreateModel(
            name='ColumnPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('EV', 'Редактировать + Просмотр'), ('VO', 'Только просмотр'), ('NA', 'Нет доступа')], default='EV', max_length=2, verbose_name='Тип доступа')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tables.column')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('column', 'user')},
            },
        ),
    ]
