# Generated by Django 5.2.3 on 2025-07-08 11:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_alter_admin_created_at_columnpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 11, 6, 59, 254003)),
        ),
        migrations.CreateModel(
            name='ColumnFilialPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('EV', 'Редактировать + Просмотр'), ('VO', 'Только просмотр'), ('NA', 'Нет доступа')], default='EV', max_length=2, verbose_name='Тип доступа')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_permissions', to='tables.column')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.filial')),
            ],
            options={
                'unique_together': {('column', 'filial')},
            },
        ),
    ]
