# Generated by Django 5.2.3 on 2025-07-09 13:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0023_alter_admin_created_at_columnfilialpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rowpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rowpermission',
            name='row',
        ),
        migrations.RemoveField(
            model_name='rowpermission',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='tablefilialpermission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tablepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tablefilialpermission',
            name='permission_type',
            field=models.CharField(choices=[('RWD', 'Редактировать + Просмотр + Удалять'), ('RNN', 'Только просмотр'), ('RWN', 'Редактировать + Просмотр'), ('NNN', 'Нет доступа')], default='RWD', max_length=3, verbose_name='Тип доступа'),
        ),
        migrations.AddField(
            model_name='tablepermission',
            name='permission_type',
            field=models.CharField(choices=[('RWD', 'Редактировать + Просмотр + Удалять'), ('RNN', 'Только просмотр'), ('RWN', 'Редактировать + Просмотр'), ('NNN', 'Нет доступа')], default='RWD', max_length=3, verbose_name='Тип доступа'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 9, 13, 13, 41, 961559)),
        ),
        migrations.CreateModel(
            name='UserFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.filial')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RowFilialPermission',
        ),
        migrations.DeleteModel(
            name='RowPermission',
        ),
        migrations.RemoveField(
            model_name='tablefilialpermission',
            name='can_view',
        ),
        migrations.RemoveField(
            model_name='tablepermission',
            name='can_view',
        ),
    ]
