# Generated by Django 5.2.3 on 2025-07-10 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0024_alter_rowpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='columnpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='columnpermission',
            name='column',
        ),
        migrations.RemoveField(
            model_name='columnpermission',
            name='user',
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 10, 13, 48, 37, 396371)),
        ),
        migrations.AlterField(
            model_name='tablefilialpermission',
            name='permission_type',
            field=models.CharField(choices=[('RWD', 'Редактировать + Просмотр + Удалять'), ('RWN', 'Редактировать + Просмотр'), ('RNN', 'Только просмотр'), ('NNN', 'Нет доступа')], default='RWD', max_length=3, verbose_name='Тип доступа'),
        ),
        migrations.AlterField(
            model_name='tablepermission',
            name='permission_type',
            field=models.CharField(choices=[('RWD', 'Редактировать + Просмотр + Удалять'), ('RWN', 'Редактировать + Просмотр'), ('RNN', 'Только просмотр'), ('NNN', 'Нет доступа')], default='RWD', max_length=3, verbose_name='Тип доступа'),
        ),
        migrations.DeleteModel(
            name='ColumnFilialPermission',
        ),
        migrations.DeleteModel(
            name='ColumnPermission',
        ),
    ]
