# Generated by Django 5.2.3 on 2025-07-10 13:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0025_alter_columnpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablepermission',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.filial'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 10, 13, 52, 24, 18831)),
        ),
    ]
