# Generated by Django 5.2.3 on 2025-07-11 08:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0026_tablepermission_filial_alter_admin_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.filial'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 8, 59, 55, 717752)),
        ),
    ]
