# Generated by Django 5.2.3 on 2025-07-11 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0027_row_filial_alter_admin_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_edit_only_you',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 13, 26, 19, 862772)),
        ),
    ]
