# Generated by Django 5.2.3 on 2025-07-11 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0029_alter_admin_created_at_alter_table_is_edit_only_you'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 13, 29, 54, 218864)),
        ),
    ]
