# Generated by Django 5.2.3 on 2025-07-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0031_alter_admin_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_edit_only_you',
            field=models.BooleanField(default=False),
        ),
    ]
