# Generated by Django 5.2.3 on 2025-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0032_alter_table_is_edit_only_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='positive_integer_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('text', 'Текст'), ('integer', 'Целое число'), ('pos_integer', 'Целое число больше нуля'), ('float', 'Число с плавающей точкой'), ('boolean', 'Логическое'), ('date', 'Дата')], default='text', max_length=12),
        ),
    ]
