# Generated by Django 5.2.3 on 2025-07-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0034_cell_email_value_alter_column_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='url_value',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('text', 'Текст'), ('integer', 'Целое число'), ('pos_integer', 'Целое число больше нуля'), ('float', 'Число с плавающей точкой'), ('boolean', 'Логическое'), ('date', 'Дата'), ('email', 'Почта'), ('url', 'Ссылка')], default='text', max_length=12),
        ),
    ]
