# Generated by Django 5.2.3 on 2025-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0035_cell_url_value_alter_column_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='file_value',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('text', 'Текст'), ('integer', 'Целое число'), ('pos_integer', 'Целое число больше нуля'), ('float', 'Число с плавающей точкой'), ('boolean', 'Логическое'), ('date', 'Дата'), ('email', 'Почта'), ('url', 'Ссылка'), ('file', 'Файл')], default='text', max_length=12),
        ),
    ]
